project:
  type: website
  output-dir: docs

format:
  html:
    theme: [lux,tufte]
    highlight-style: gruvbox-dark
    css: notes/styles.css
    toc: true
    code-tools: true

projects:
  - notes
