project:
  type: website
  output-dir: ../docs/notes
  render:
    - "about.qmd"
    - "index.qmd"

website:
  title: "Formal complexity"
  page-navigation: true
  sidebar:
    style: docked
    search: true
    contents:
    - about.qmd
    - index.qmd
    - section: "Formal preliminaries"
    - section: "Regular languages"
    - section: "Context-free languages"
    - section: "Context-sensitivity"
    - section: "Mild context-sensitivity"
    - section: "Recursive and recursively enumerable languages"

format:
  html:
    theme: [lux,tufte]
    highlight-style: gruvbox-dark
    css: styles.css
    toc: true
    code-tools: true

# filters:
  # - line-highlight
