---
title: "Syllabus"
bibliography: ../formal_complexity.bib
csl: https://raw.githubusercontent.com/citation-style-language/styles/master/chicago-author-date.csl
---

Welcome to Formal Complexity!^[Listed as both LIN4930 and LIN6932 at [one.uf.edu](https://one.uf.edu/).]

I'm [Julian Grove](https://juliangrove.github.io/) - I'm an Assistant Professor in the [Linguistics Department](https://lin.ufl.edu/) (where this course is offered).

Here is my contact info:

- Office: 4108 Turlington
- Phone: 352.294.7456
- Email: first name dot last name at ufl dot edu
- Office hours: Mondays, 1pm-2pm and by appointment

Check out the [About](/about.html) page for more info about me and this site.

Here are some facts about this course:

- It takes place in [Matherly](https://campusmap.ufl.edu/#/index/0406) 0108.
- It happens on Mondays, Wednesdays, and Fridays.
- It runs from 11:45am - 12:35pm.

## Bird's-eye view

The goal of this course is to acquaint you with the study of formal linguistic complexity.
Specifically, we will cover complexity classes of languages, focusing on regular, context-free, context-sensitive, recursive, and recursively enumerable languages.
We'll explore each class of languages in terms of:
(a) the formal grammars that generate languages in that class;
and (b) the abstract machines that recognize languages in the class.
Along the way, we'll discuss hypotheses about the complexity of natural language (e.g., the subregular hypothesis in phonology, and the hypothesis that natural language syntax is mildly context-sensitive), as well as some grammar formalisms which have been proposed to capture these hypotheses.

## Attendance and class participation

Come to class!
You're likely to do better in the course if you come than if you don't.

When you're here, participate!
You'll get more out of the class if you do, and it'll be more fun.

## Assignments and grading

### Grading

Your work in this course will consist of [seven (7) problem sets]{.underline}---sometimes based on assigned readings---as well as a [take-home final exam]{.underline}.
The problem sets will be due every other week (see [the calendar](#sec-calendar)). 
Each assignment will be available on this site and will typically feature problems selected from @partee_mathematical_1993 / @partee_mathematical_1990.
Please either turn in a physical copy of your responses the beginning of the class on which the assignment is due, or upload them to Canvas before class starts.

The problem sets will be graded on a 100-point scale.
Each problem set will provide a precise breakdown of how points are allocated.

These will account for 70% of your grade, and a take-home final exam, for 30%.
The take-home final will be due on December 9th at 5pm.
It will be formatted similarly to the assignments, but it will be a little more substantial.

The following grading scale will be used to determine course grades:

|                  |                  |                  |
|------------------|------------------|------------------|
| 93.5 ≤ A ≤ 100   | 89.5 ≤ A- < 93.5 |                  |
| 86.5 ≤ B+ < 89.5 | 83.5 ≤ B < 86.5  | 79.5 ≤ B- < 83.5 |
| 76.5 ≤ C+ < 79.5 | 74.5 ≤ C < 76.5  | 69.5 ≤ C- < 74.5 |
| 66.5 ≤ D+ < 69.5 | 64.5 ≤ D < 66.5  | 59.5 ≤ D- < 64.5 |

### Collaboration (including with chatbots)

We'll talk about this in class.
Basically:

- Complete the assignments yourself.
- If you worked with someone else in the class (or a chatbot) on an assignment, please indicate that you did.
  If you used a chatbot, include a note with your assignment describing how you used it.
  Please specify:
  - the prompt you used;
  - the output produced.
  Please don't use a chatbot to extract an answer to a problem.

### Missed or late work

Late work will be docked 10 points each day it is late.
It will not be accepted once it is four days late.
If you need an extension, ask for one---just do it prior to the due date.

## Zulip

There is a Zulip site for this course at [uf-formal-complexity-2026.zulipchat.com](https://uf-formal-complexity-2026.zulipchat.com/).
All communication about the course should be done through Zulip.
For example, rather than email me, please send me a message there.
We'll also use Zulip to host discussions of the course material.
You can post (and answer!) questions there.
(I may chime in, as well.)

## University Honesty Policy

UF students are bound by The Honor Pledge which states, "We, the members of the University of Florida community, pledge to hold ourselves and our peers to the highest standards of honor and integrity by abiding by the Honor Code."
On all work submitted for credit by students at the University of Florida, the following pledge is either required or implied:
"On my honor, I have neither given nor received unauthorized aid in doing this assignment."
The Honor Code ([policy.ufl.edu/regulation/4-040/](https://policy.ufl.edu/regulation/4-040/)) specifies a number of behaviors that are in violation of this code and the possible sanctions.
Furthermore, you are obligated to report any condition that facilitates academic misconduct to appropriate personnel.
If you have any questions or concerns, please consult with the instructor.

## Counseling and Wellness Center

Contact information for the Counseling and Wellness Center:

- [counseling.ufl.edu](http://www.counseling.ufl.edu/)
- Phone: 352.392.1575

Contact information for the University Police Department:

- [police.ufl.edu](https://police.ufl.edu/contact/)
- Phone: 352.392.1111

## Accommodations for Students with Disabilities

Students with disabilities requesting accommodations should first register with the Disability Resource Center (352.392.8565, [disability.ufl.edu](https://disability.ufl.edu/)) by providing appropriate documentation.
Once registered, students will receive an accommodation letter which must be presented to the instructor when requesting accommodation.
Students with disabilities should follow this procedure as early as possible in the semester.

## Academic polices and resources

Available here:

- [syllabus.ufl.edu/syllabus-policy/uf-syllabus-policy-links/](https://syllabus.ufl.edu/syllabus-policy/uf-syllabus-policy-links/)

## Calendar {#sec-calendar}

| Date           | Topic                                             | Reading | Assignment |
|----------------|---------------------------------------------------|---------|------------|
| Fri., Aug. 21  | Introduction                                      |         |            |
| Mon., Aug. 24  | Set-theoretic foundations and languages           |         | View       |
| Wed., Aug. 26  | Set-theoretic foundations and languages           |         |            |
| Fri., Aug. 28  | Set-theoretic foundations and languages           |         |            |
| Mon., Aug. 31  | Finite languages and regular languages            |         |            |
| Wed., Sept. 2  | Regular languages, expressions, and grammars      |         |            |
| Fri., Sept. 4  | Regular languages, expressions, and grammars      |         |            |
| Mon., Sept. 7  | No class: Labor Day                               |         | View       |
| Wed., Sept. 9  | Regular languages, expressions, and grammars      |         |            |
| Fri., Sept. 11 | finite-state automata                             |         |            |
| Mon., Sept. 14 | finite-state automata                             |         |            |
| Wed., Sept. 16 | The pumping lemma for regular languages           |         |            |
| Fri., Sept. 18 | No class: Julian away                             |         |            |
| Mon., Sept. 21 | The pumping lemma for regular languages           |         | View       |
| Wed., Sept. 23 | Regular languages and natural language phonology  |         |            |
| Fri., Sept. 25 | Regular languages and natural language morphology |         |            |
| Mon., Sept. 28 | Context-free languages                            |         |            |
| Wed., Sept. 30 | Context-free languages                            |         |            |
| Fri., Oct. 2   | Pushdown automata                                 |         |            |
| Mon., Oct. 5   | Pushdown automata                                 |         | View       |
| Wed., Oct. 7   | Context-sensitive languages                       |         |            |
| Mon., Oct. 12  | Context-sensitive languages                       |         |            |
| Wed., Oct. 14  | Linear bounded automata                           |         |            |
| Fri., Oct. 16  | No class: Julian away                             |         |            |
| Mon., Oct. 19  | Linear bounded automata                           |         | View       |
| Wed., Oct. 21  | Is natural language syntax context-free?          |         |            |
| Fri., Oct. 23  | Is natural language syntax context-free?          |         |            |
| Mon., Oct. 26  | Minimalist grammars                               |         |            |
| Wed., Oct. 28  | Minimalist grammars                               |         |            |
| Fri., Oct. 30  | Minimalist grammars                               |         |            |
| Mon., Nov. 2   | Multiple context-free grammars                    |         | View       |
| Wed., Nov. 4   | Multiple context-free grammars                    |         |            |
| Fri., Nov. 6   | Multiple context-free categorial grammars         |         |            |
| Mon., Nov. 9   | Combinatory categorial grammars                   |         |            |
| Fri., Nov. 13  | Combinatory categorial grammars                   |         |            |
| Mon., Nov. 16  | Combinatory categorial grammars                   |         | View       |
| Wed., Nov. 18  | Recursive languages and Turing machines           |         |            |
| Fri., Nov. 20  | Recursive languages and Turing machines           |         |            |
| Mon., Nov. 30  | Recursively enumerable languages / wrap-up        |         |            |
| Wed., Dec. 2   | Recursively enumerable languages / wrap-up        |         |            |
